### ISSUE TITLE
Corresponding paper

### ISSUE THREAD

**Issue by dhuQChen** [Mayy1994/RL_segmentation#2]
can you give the link for corresponding paper of this code? Thank you!

**Comment by LGDuan** [comment]
I really want to read the corresponding paper of this code, I really need it, can you give the link?Thanks a lot!

**Comment by Mayy1994** [comment]
I am sorry that since this paper is under review, I can't release it now. If this paper is accepted in the future, I will send you the link as soon as possible.
Should you have any problems with this code, you can also send an email to me. My email address is jingxiong9-c@my.cityu.edu.hk
Hope you can understand that. Thanks!

**Comment by LGDuan** [comment]
Thank you very much for your reply and agreeing to give me the link of your paper in the future！You're so kind！I sincerely hope that your paper will be accepted soon in the future！Thank you for your willingness to help me. Best wishes to you!



At 2020-04-30 11:14:31, "Mayy1994" <notifications@github.com> wrote:

I am sorry that since this paper is under review, I can't release it now. If this paper is accepted in the future, I will send you the link as soon as possible.
Should you have any problems with this code, you can also send an email to me. My email address is jingxiong9-c@my.cityu.edu.hk
Hope you can understand that. Thanks!

**Comment by Mayy1994** [comment]
Sorry for the late reply. The corresponding paper is "Edge-Sensitive Left Ventricle Segmentation Using Deep Reinforcement Learning". https://www.mdpi.com/1424-8220/21/7/2375/htm
